### ISSUE TITLE
Compiler with 2 different classes with the same (simple) name.

### ISSUE THREAD

**Issue by rsearls** [Intersmash/intersmash#72] opened 2023-08-16 16:09 UTC
In creating a SOAP testcase I have encountered a compiler issue.
>> In Java, you cannot import two different classes with the same (simple) name.

code fragment
  import jakarta.xml.ws.Service;
  import org.jboss.intersmash.tools.annotations.Service;
  ...
  @Slf4j
  @Intersmash({@Service(WsWildflyBootableOpenShiftJarApplication.class) })
  public class WsWildflyBootableOpenShiftJarTest {
    ...
    URL wsdlURL = new URL(baseURL + "?wsdl");
    Service service = Service.create(wsdlURL, serviceName);
    Endpoint proxy = service.getPort(Endpoint.class);
    ...

The name conflict is between jakarta.xml.ws.Service and 
org.jboss.intersmash.tools.annotations.Service

jakarta.xml.ws.Service is required in order to make the connection to the endpoint.
org.jboss.intersmash.tools.annotations.Service is required to identify the
configuring class to intersmash.

Specifying the fully qualified class name of each class does not resolve the failure.

For future users creating SOAP tests it would be helpful if
org.jboss.intersmash.tools.annotations.Service were renamed so as not
to conflict with jakarta.xml.ws.Service.

There is a work around. 
>> In these  situations, the user can import one name, but use the other with 
the fully qualified class name.  Or remove both imports and use the fully
qualified class name for both uses.

(e.g.)
  //--import jakarta.xml.ws.Service;
  import org.jboss.intersmash.tools.annotations.Service;
  ...
  @Slf4j
  @Intersmash({@Service(WsWildflyBootableOpenShiftJarApplication.class) })
  public class WsWildflyBootableOpenShiftJarTest {
    ...
    URL wsdlURL = new URL(baseURL + "?wsdl");
    jakarta.xml.ws.Service service = jakarta.xml.ws.Service.create(wsdlURL, serviceName);
    Endpoint proxy = service.getPort(Endpoint.class);
    ...

**Comment by fabiobrz** [comment] 2023-08-21 15:11
Thanks for creating the issue @rsearls.
I am wondering whether we should identify this as a bug or just a normal behavior and consider the workaround that you proposed as the actual solution.
I am for the latter, since we'd face this very issue in any Java sources that would use two (or more) classes with the same simple name. And it would make sense to import the most used one, while using the full name for the other(s).
WDYT?

That being said, we0re still working on a first release, so no APIs would be broken in case we decide for renaming `@Service`to something else.

**Comment by rsearls** [comment] 2023-08-21 15:21
@fabiobrz I don't have a preference on this issue.

**Comment by fabiobrz** [comment] 2023-09-08 11:41
> @fabiobrz I don't have a preference on this issue.

Ok, thanks @rsearls - let's rely on the above reasoning and close this as not a bug.

**Closed by fabiobrz** 2023-09-08 11:41 UTC
Labels: wontfix
